---
- name: Dump assetic assets
  shell: chdir={{ansistrano_release_path.stdout}}
    SYMFONY_ENV={{symfony_env}} APP_ENV={{symfony_env}} {{symfony_php_path}} {{symfony_console_path}} assetic:dump {{ symfony_assetic_options }}
